/*
 * This source file was generated by the Gradle 'init' task
 */
package first;

import org.springframework.context.ApplicationContext;

public class Main {
    public static void main(String[] args)
    {
        Engine engine = new Engine("V8", "Ford");
    }



    ApplicationContext context = new org.springframework.context.annotation.AnnotationConfigApplicationContext(BeanConfig.class);

    Car car = context.getBean(Car.class);

    car.drive();
}
